### ISSUE TITLE
Add support for parsing custom link element <geom_group>

### ISSUE THREAD

**Issue by DavidB-CMU** [personalrobotics/or_urdf#19]
This will add support for parsing URDF files that may have links containing one or more optional \<geom_group> elements. This allows us to specify additional collision geometry for a robot.

Example use case: 
The HERB robot model uses low resolution meshes for the fingers to speed-up collision checking. 
If you want to do higher resolution collision checking for grasping then you can programmatically change the geometry group for the hand links. 
The bottom-right image shows the geometry group "fine_collision" which has higher resolution geometry for the Barrett WAM gripper. 
![herb_geom_groups](https://cloud.githubusercontent.com/assets/14189705/12285070/44de4950-b984-11e5-8d7e-1104b12cf301.png)

**Comment by psigen** [comment]
Is this issue closed now?

**Comment by DavidB-CMU** [comment]
Yes #20 has been merged.
