### ISSUE TITLE
Advertised support for package:// URLs doesn't work?

### ISSUE THREAD

**Issue by cdellin** [personalrobotics/or_urdf#8]
The README mentions support for `package://` URLs, but the following doesn't work:

    m.SendCommand('load package://herb_description/robots/herb.urdf package://herb_description/robots/herb.srdf')
    [ERROR] [1427416657.641067879]: Could not open file [package://herb_description/robots/herb.urdf] for parsing.

Is this a supported use case?

**Comment by mkoval** [comment]
I meant that package URIs are supported for mesh resources. :smile:

I see no reason why they shouldn't work for specifying the URDF and SRDF files, too. I'll take a look at adding support.

**Comment by cdellin** [comment]
Ah, cool, that makes sense.

But yes, support for this would be cool, thanks!

**Comment by mkoval** [comment]
Implemented in #12. Have fun! :smile:
